#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <challenge_name>"
    exit 1
fi

set -e
set -u
set -o pipefail

CHALLENGE_NAME=$1

mkdir -p "$CHALLENGE_NAME"
cd $CHALLENGE_NAME

scp -r 'hacker@dojo.pwn.college:/challenge/.' .

# detect the challenge binary name
BINARY=$(find . -maxdepth 1 -type f -print0 | xargs -0 file | grep -m 1 "ELF" | awk -F: '{print $1}')


if [[ "$BINARY" == *.ko ]]; then
    cat << EOF > "./solve.py"
from pwn import *

prog = "$BINARY"
ko = ELF(prog)
s = ssh('hacker', 'dojo.pwn.college')

process("make")
s.upload("./pwn", "pwn")
s.shell("vm start")

io = process(
    ['ssh', '-tt', 'hacker@dojo.pwn.college', 'vm', 'connect'],
    stdin=PTY, stdout=PTY, stderr=PTY
)
io.recvuntil(b'$')
io.sendline(b"chmod +x ./pwn")
io.interactive(prompt=None)
EOF

    cat <<EOF > Makefile
all: pwn

pwn: pwn.c
$(printf '\t')toolup cc x86_64-unknown-linux-musl -static ./pwn.c -o pwn
EOF

    cat << EOF > "./pwn.c"
#include <stdio.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <unistd.h>

int main() {
  int fd = open("/proc/pwncollege", 0);

  char *args[] = {"/bin/sh", NULL};
  execve("/bin/sh", args, NULL);
  return 0;
}
EOF

else
    INTERP=$(patchelf --print-interpreter "$BINARY")

    # download all needed libraries
    while IFS= read -r line; do
        [[ "$line" != /* ]] && line="/lib/x86_64-linux-gnu/$line"
        [[ "$line" == *"libc.so.6"* ]] && LIBC="$line"

        [[ "$line" == *"libcapstone.so.5"* ]] && line="/lib/libcapstone.so.5"
        scp "hacker@dojo.pwn.college:$line" .
    done < <(patchelf --print-needed "$BINARY")

    scp "hacker@dojo.pwn.college:$INTERP" .

    cp $BINARY "$BINARY"-patched

    patchelf "$BINARY"-patched --set-rpath . --set-interpreter ./ld-linux-x86-64.so.2
    patchelf --replace-needed /challenge/lib/libc.so.6 libc.so.6 "$BINARY"-patched

    # some debug info go missing in the patched elf, so we add it again. (not sure if there is a better way)
    #objcopy --only-keep-debug $BINARY challenge.debug
    #objcopy --add-gnu-debuglink=challenge.debug "$BINARY"-patched

    cat << EOF > "./solve.py"
from pwn import *

prog = "$BINARY-patched"

elf = ELF(prog)
context.binary = elf
context.aslr = False

if "remote" in sys.argv:
    session = ssh('hacker', 'dojo.pwn.college')
    p = session.process(f'/challenge/$BINARY')
else:
    if "gdb" in sys.argv:
        p = gdb.debug(prog)
    else:
        p = process(prog)

p.interactive()
EOF
fi

uv init .
uv add pwntools
rm -f README.md main.py

echo "Challenge folder created"
