#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <challenge_name>"
    exit 1
fi

CHALLENGE_NAME=$1

mkdir -p "$CHALLENGE_NAME"

# copy challenge files
scp -r hacker@dojo.pwn.college:/challenge/* "$CHALLENGE_NAME/"

cat << 'EOF' > "./$CHALLENGE_NAME/solve.py"
from pwn import *
import sys

prog = sys.argv[1]

elf = ELF(prog)
context.binary = elf
if "remote" in sys.argv:
    s = ssh('hacker', 'dojo.pwn.college')
    p = s.shell(f'/challenge/{prog}')
else:
    p = process(prog)

p.interactive()
EOF

echo "Challenge folder created"
cd $CHALLENGE_NAME
uv init .
uv add pwntools
rm -f README.md main.py

